### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by andreyruby**
- replace extra dependency (`sematic`) gem with custom implementation that uses Gem::Version
- remove not required arrays allocations in ServerMiddleware
- Add github workflow to check different ruby versions
- Update gems

### CODE REVIEW

**Comment by alg** [comment]
@aglushkov Thanks for the PR.

I'm disagreeing with getting rid of `semantic` gem, unless we can provide access to minor and patch levels of version without it. By leaving just the `major` version you limit any potential user of the library to that. That's what the default policy does as a common use-case, but it doesn't mean every policy should always be based on major version only. IMO, version is a version and you are free to decide on your own policy.

**Comment by andreyruby** [comment]
@alg I've update PR

Add custom SemVer parser based on official regexp on semver.org. 

Keep `major`, `minor`, `patch`, `pre` and `build` methods that exists at `semantic` gem

Added method for comparision of two versions based on semver.org algorithm

**Comment by alg** [comment]
@aglushkov Thanks, mate. I'll give it a look over weekend.

**Comment by alg** [comment]
@aglushkov Looked through. Looks like a lot of improvement there, thanks.

One place I didn't quite get is moving development dependencies from gemspec into Gemfile. I read there's an issue with installing dependencies of dev dependencies to make them work, but doesn't moving dev deps to Gemfile make them install to production code? We don't really want rspec and simplecov in there.

**Comment by andreyruby** [comment]
This gems in Gemfile are only for development. We load them in rspec_helper during `require 'bundler/setup'`.

Currently its probably the same as using `add_development_dependency`

But this approach will help to omit conflicts if we want to run tests with different (for example) Rails versions, as we can have different gems in different Gemfiles

**Pull request merged**
